apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: shattered-realms
  labels:
    app: sro-accounts
    version: v1
    istio-injection:
      enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sro-accounts
      version: v1
  template:
    metadata:
      labels:
        app: sro-accounts
        version: v1
        istio-injection:
          enabled
    spec:
      containers:
        - name: accounts
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/accounts:latest
          imagePullPolicy: Always
          env:
            - name: PS_AUTH_JWT_PRIVATE_KEY_PATH
              value: "/etc/sro/auth/keys/key"
            - name: PS_AUTH_JWT_PUBLIC_KEY_PATH
              value: "/etc/sro/auth/keys/key.pub"
            - name: SRO_AUTH_MODE
              value: "release"
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: mysql-db
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: sro-jwt.default
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: mysql-db
          secret:
            secretName: sro-db.default
---
apiVersion: v1
kind: Service
metadata:
  name: sro-accounts
  namespace: shattered-realms
  labels:
    app: sro-accounts
    version: v1
    istio-injection:
      enabled
spec:
  type: ClusterIP
  selector:
    app: sro-frontend
    version: v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http